name: AttackSpeedRemover
main: fr.tenebrae.AttackSpeedRemover.Main
authors: [Arektor]
version: 2.1.3
description: AttackSpeed remover
commands:
   asr:
      description: AttackSpeedRemover commands
      usage: /<command>