name: AttackSpeedRemover
main: fr.tenebrae.AttackSpeedRemover.Main
authors: [Arektor]
version: 1.3.1
description: AttackSpeed remover
commands:
   asr:
      description: AttackSpeedRemover commands
      usage: /<command>